
tasks:
  - init: pip install -r requirements.txt # runs during prebuild
    command: python app.py
    openIn: bottom
  - openMode: split-right
    command: echo SplitTerminal
  - openIn: left
    command: echo LeftPanelTerminal
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python